services:
  injector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orquestrador
    environment:
      - PORT=${PORT}
      - AMQP_URL=${AMQP_URL}
      - QUEUE_NAME=${QUEUE_NAME}
      - GRAPH_DB_URI=${GRAPH_DB_URI}
      - GRAPH_DB_USERNAME=${GRAPH_DB_USERNAME}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - IOT_HUB_HOST=${IOT_HUB_HOST}
      - AZURE_IOTHUB_CONNECTION_STRING=${AZURE_IOTHUB_CONNECTION_STRING}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
