
services:
  orquestrador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orquestrador
    environment:
      - PORT=${PORT}
      - AMQP_URL=${AMQP_URL}
      - GRAPH_DB_URI=${GRAPH_DB_URI}
      - GRAPH_DB_USERNAME=${GRAPH_DB_USERNAME}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
