services:
  injector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: injector
    environment:
      - PORT=${INJECTOR_PORT}
      - AMQP_URL=${AMQP_URL}
      - QUEUE_NAME=${QUEUE_NAME}
      - GRAPH_DB_URI=${GRAPH_DB_URI}
      - GRAPH_DB_USERNAME=${GRAPH_DB_USERNAME}
      - GRAPH_DB_PASSWORD=${GRAPH_DB_PASSWORD}
      - AZURE_IOT_HOST=${AZURE_IOT_HOST}
      - AZURE_IOT_DEVICE_ID=${AZURE_IOT_DEVICE_ID}
      - AZURE_IOT_USERNAME=${AZURE_IOT_USERNAME}
      - AZURE_IOT_PASSWORD=${AZURE_IOT_PASSWORD}
    ports:
      - "${INJECTOR_PORT}:${INJECTOR_PORT}"
    restart: unless-stopped
