services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_LOAD_DEFINITIONS: "/etc/rabbitmq/definitions.json"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin123"
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
